Repository itsproutorgua/olx-killer-monorepo, pull requests merged in 2024-11, with the labels that each got.

#24 Endpoint new products
  backend/apps/products/admin/filters/popular_category.py
  backend/apps/products/admin/product.py
  backend/apps/products/serializers/product/product_latest.py
  backend/apps/products/urls.py
  backend/apps/products/views/__init__.py
  backend/apps/products/views/products_latest.py
Labels: Review effort [1-5]: 3

#25 refactor display categories on cat page
  frontend/src/entities/category/model/category.types.ts
  frontend/src/features/page-pagination/ui/page-pagination.tsx
  frontend/src/pages/catalog/catalog-page.tsx
  frontend/src/pages/layouts/root-layout.tsx
  frontend/src/shared/config/i18next/i18next.ts
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/colors.const.ts
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/spinner.tsx
  frontend/src/shared/ui/index.ts
  frontend/src/shared/ui/page-loader.tsx
  frontend/src/widgets/category-navbar/ui/cat-navbar-desktop.tsx
  frontend/src/widgets/category-navbar/ui/cat-navbar-mobile.tsx
  frontend/src/widgets/category-navbar/ui/category-navbar-skeleton.tsx
  frontend/src/widgets/category-navbar/ui/category-navbar.tsx
  frontend/src/widgets/filters-bar/mock/filters.mock.ts
  frontend/src/widgets/filters-bar/ui/filters-form.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs-item.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs.tsx
  frontend/src/widgets/filters-sheet/ui/filters-sheet.tsx
  frontend/src/widgets/page-toolbar/ui/page-toolbar.tsx
  frontend/tailwind.config.ts
Labels: Review effort [1-5]: 3

#26 Testing of Auth0 access token sending to the backend
  frontend/src/app/providers/providers.tsx
  frontend/src/entities/user/user-menu.tsx
Labels: Review effort [1-5]: 3

#27 Testing registration of user using idToken
  frontend/src/entities/user/user-menu.tsx
Labels: Review effort [1-5]: 3

#28 Styles and bugs are fixed, also added burger-menu on mobile devices f…
  frontend/src/features/lang-switcher/lang-switcher.tsx
  frontend/src/features/top-bar/top-bar.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/ui/icons/bottom-bar-home.tsx
  frontend/src/shared/ui/icons/carouselThumbnailNext.tsx
  frontend/src/shared/ui/icons/carouselThumbnailPrevious.tsx
  frontend/src/shared/ui/icons/catalog-menu.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/scrollableListArrowLeft.tsx
  frontend/src/shared/ui/icons/scrollableListArrowRight.tsx
  frontend/src/shared/ui/shadcn-ui/dialog.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/product-card/ui/product-card.tsx
  frontend/src/widgets/product-details/ui/contact-seller-card.tsx
  frontend/src/widgets/product-details/ui/product-carousel.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
Labels: Review effort [1-5]: 4

#29 Bugfixes on the product card description size and asideNav
  frontend/src/features/top-bar/top-bar.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/product-card/ui/product-card.tsx
Labels: Review effort [1-5]: 2

#30 get products with sort params
  frontend/src/app/providers/providers.tsx
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/product/library/product.consts.ts
  frontend/src/entities/product/model/product.types.ts
  frontend/src/shared/api/index.ts
  frontend/src/shared/api/query-client.ts
  frontend/src/shared/constants/app.const.ts
  frontend/src/shared/ui/shadcn-ui/select.tsx
  frontend/src/widgets/best-deals/best-deals.tsx
  frontend/src/widgets/product-grid/library/hooks/index.ts
  frontend/src/widgets/product-grid/library/hooks/use-products.tsx
  frontend/src/widgets/product-grid/library/index.ts
  frontend/src/widgets/product-grid/ui/product-grid-mobile.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
  frontend/src/widgets/product-grid/ui/product-list.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
  frontend/src/widgets/sort-button/sort-button.tsx
Labels: Review effort [1-5]: 3

#33 New API Pattern implemented, styles/bugs fixed as per trello
  frontend/src/entities/category/api/category.api.ts
  frontend/src/entities/category/library/hooks/use-categories.tsx
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/product/library/hooks/use-product.tsx
  frontend/src/features/lang-switcher/lang-switcher.tsx
  frontend/src/features/product/write-seller/write-seller.tsx
  frontend/src/pages/catalog/catalog-page.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/library/utils/capitalize-first-word.ts
  frontend/src/shared/ui/error/fetch-error.tsx
  frontend/src/shared/ui/icons/mainLogo.tsx
  frontend/src/shared/ui/loaders/product-page.loader.tsx
  frontend/src/shared/ui/logo.tsx
  frontend/src/shared/ui/skeletons/aside-category-skeleton.tsx
  frontend/src/shared/ui/skeletons/best-deals-skeleton.tsx
  frontend/src/shared/ui/skeletons/index.ts
  frontend/src/shared/ui/skeletons/popular-category-skeleton.tsx
  frontend/src/shared/ui/skeletons/product-page-skeleton.tsx
  frontend/src/shared/ui/skeletons/product-slider-skeleton.tsx
  frontend/src/shared/ui/skeletons/scrollable-products-skeleton.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/best-deals/best-deals.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/footer/footer.tsx
  frontend/src/widgets/new-products/new-products.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/other-products-by-seller/products-by-seller.tsx
  frontend/src/widgets/other-products-by-seller/ui/products-by-seller-slider.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/product-details/ui/product-location.tsx
  frontend/src/widgets/product-grid/library/hooks/use-products.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
  frontend/src/widgets/similar-products/similar-products.tsx
  frontend/src/widgets/similar-products/ui/similar-products-slider.tsx
Labels: Review effort [1-5]: 3
