Repository itsproutorgua/olx-killer-monorepo, pull requests merged in 2024-10, with the labels that each got.

#2 update tailwind config
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/styles/index.css
  frontend/tailwind.config.ts
Labels: enhancement, dependencies, Review effort [1-5]: 3

#3 minor changes added according to design modifications
  frontend/src/features/product/show-number/show-number.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/ui/icons-pack.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/footer/footer.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
  frontend/tailwind.config.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#4 fixed header styles
  .gitignore
  frontend/src/entities/user/ui/user-button.tsx
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/lang-switcher/lang-switcher.tsx
  frontend/src/features/search-bar/search-bar.tsx
  frontend/src/shared/ui/icons-pack.tsx
  frontend/src/shared/ui/icons/heart.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/user-rounded.tsx
  frontend/src/shared/ui/logo.tsx
  frontend/src/shared/ui/shadcn-ui/select.tsx
  frontend/src/widgets/cart-button/cart-button.tsx
  frontend/src/widgets/cart-button/index.ts
  frontend/src/widgets/favorite-button/favorite-button.tsx
  frontend/src/widgets/header/header.tsx
  frontend/src/widgets/header/ui/nav-toolbar.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#6 Styles modified according to design, bottom bar for mobile devices added
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/olx-killer-monorepo.iml
  .idea/prettier.xml
  .idea/vcs.xml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/entities/user/ui/user-button.tsx
  frontend/src/features/announcement/add-announcement/add-announcement.tsx
  frontend/src/features/lang-switcher/lang-switcher.tsx
  frontend/src/pages/home/home-page.tsx
  frontend/src/pages/layouts/root-layout.tsx
  frontend/src/shared/api/axios.ts
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/app.const.ts
  frontend/src/shared/ui/icons-pack.tsx
  frontend/src/shared/ui/icons/bottom-bar-menu.tsx
  frontend/src/shared/ui/icons/cart-icon.tsx
  frontend/src/shared/ui/icons/circle-plus.tsx
  frontend/src/shared/ui/icons/heart.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/user-rounded.tsx
  frontend/src/shared/ui/loaders/aside-category.loader.tsx
  frontend/src/shared/ui/loaders/popular-categories.loader.tsx
  frontend/src/shared/ui/logo.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/best-deals/best-deals.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/footer/footer.tsx
  frontend/src/widgets/hero/ui/hero-slider.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/new-products/new-products.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/product-card/product-card.tsx
  frontend/src/widgets/promo/promo.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
  frontend/tailwind.config.ts
Labels: enhancement, Review effort [1-5]: 4, Other

#7 api changed to main server
  frontend/src/entities/category/model/category.types.ts
  frontend/src/shared/constants/app.const.ts
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
Labels: enhancement, Review effort [1-5]: 2

#9 language bag fixed, product cards on mobile devices error fixed
  frontend/src/app/routes/routes.tsx
  frontend/src/shared/ui/loaders/product-card-small.loader.tsx
  frontend/src/widgets/best-deals/best-deals.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/other-products-by-seller/products-by-seller.tsx
  frontend/src/widgets/other-products-by-seller/ui/products-by-seller-slider.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/similar-products/similar-products.tsx
  frontend/src/widgets/similar-products/ui/similar-products-slider.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#10 prices depends on language bugfixes, loaders modifications, sliders r…
  .gitignore
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/product-card/library/product-card.helpers.ts
  frontend/src/widgets/product-slider/product-slider.tsx
Labels: enhancement, Review effort [1-5]: 3, bug fix

#12 popover for long titles in subcategories added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/shared/ui/shadcn-ui/hover-card.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
Labels: Review effort [1-5]: 3

#13 add pagination on category page, scroll tot top
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/styles/index.css
  frontend/src/features/page-pagination/ui/page-pagination.tsx
  frontend/src/pages/catalog/catalog-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/app.const.ts
  frontend/src/shared/library/hooks/index.ts
  frontend/src/shared/library/hooks/use-query-params.ts
  frontend/src/widgets/category-navbar/ui/cat-navbar-desktop.tsx
  frontend/src/widgets/page-toolbar/ui/page-toolbar.tsx
  frontend/src/widgets/product-grid/ui/product-grid-mobile.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
  frontend/src/widgets/sort-button/sort-button.tsx
Labels: Review effort [1-5]: 3

#14 add product-grid-mobile, add translations for category-navbar button
  frontend/src/pages/catalog/catalog-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/widgets/category-navbar/ui/cat-navbar-mobile.tsx
  frontend/src/widgets/product-grid/ui/index.ts
  frontend/src/widgets/product-grid/ui/product-grid-mobile.tsx
Labels: Review effort [1-5]: 3

#15 Product page integrated with backend, translations added, styles fixed
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/product/model/product-date.helper.ts
  frontend/src/entities/product/model/product.types.ts
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/query-keys.const.ts
  frontend/src/shared/library/utils/generate-crumbs.ts
  frontend/src/shared/ui/breadcrumbs.tsx
  frontend/src/shared/ui/loaders/product-page.loader.tsx
  frontend/src/widgets/login-card/login-card.tsx
  frontend/src/widgets/product-details/product-details.tsx
  frontend/src/widgets/product-details/ui/contact-seller-card.tsx
  frontend/src/widgets/product-details/ui/product-carousel.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/product-details/ui/product-location.tsx
  frontend/src/widgets/product-details/ui/product-seller.tsx
Labels: Review effort [1-5]: 3

#16 refactor desktop filters-bar
  frontend/src/app/styles/index.css
  frontend/src/features/filter-bar/index.ts
  frontend/src/features/filter-bar/mock/index.ts
  frontend/src/features/filter-bar/ui/filters-bar.tsx
  frontend/src/features/filter-bar/ui/filters-desktop.tsx
  frontend/src/features/filter-bar/ui/filters-mobile.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/colors.const.ts
  frontend/src/shared/constants/index.ts
  frontend/src/shared/ui/shadcn-ui/checkbox.tsx
  frontend/src/shared/ui/shadcn-ui/sheet.tsx
  frontend/src/shared/ui/shadcn-ui/slider.tsx
  frontend/src/widgets/filters-bar/index.ts
  frontend/src/widgets/filters-bar/mock/filters.mock.ts
  frontend/src/widgets/filters-bar/mock/index.ts
  frontend/src/widgets/filters-bar/ui/filters-bar.tsx
  frontend/src/widgets/filters-bar/ui/filters-form.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs-content.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs-footer.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs-header.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs-item.tsx
  frontend/src/widgets/filters-bar/ui/filters-tabs.tsx
  frontend/src/widgets/filters-bar/ui/index.ts
  frontend/src/widgets/filters-button/filters-button.tsx
  frontend/src/widgets/filters-button/index.ts
  frontend/src/widgets/filters-sheet/index.ts
  frontend/src/widgets/filters-sheet/ui/filters-sheet.tsx
  frontend/src/widgets/filters-sheet/ui/index.ts
  frontend/src/widgets/page-toolbar/ui/page-toolbar-mobile.tsx
  frontend/src/widgets/page-toolbar/ui/page-toolbar.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
  frontend/tailwind.config.ts
Labels: Review effort [1-5]: 3

#17 Product page bug fixes and user experience improvements
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/new-products/new-products.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/other-products-by-seller/products-by-seller.tsx
  frontend/src/widgets/other-products-by-seller/ui/products-by-seller-slider.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
  frontend/src/widgets/similar-products/similar-products.tsx
  frontend/src/widgets/similar-products/ui/similar-products-slider.tsx
Labels: Review effort [1-5]: 3

#18 Aside nav/popover fixes
  frontend/src/widgets/aside-nav/aside-nav.tsx
Labels: Review effort [1-5]: 2

#19 modal added for images
  frontend/package-lock.json
  frontend/package.json
  frontend/src/shared/ui/shadcn-ui/carousel.tsx
  frontend/src/shared/ui/shadcn-ui/dialog.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/product-details/ui/product-carousel.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
Labels: Review effort [1-5]: 3

#22 main page design modifications implemented
  frontend/src/features/search-bar/index.ts
  frontend/src/features/search-bar/search-bar.tsx
  frontend/src/features/top-bar/index.ts
  frontend/src/features/top-bar/top-bar.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/ui/icons/mainLogo.tsx
  frontend/src/shared/ui/icons/searchIconRounded.tsx
  frontend/src/shared/ui/logo.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/footer/footer.tsx
  frontend/src/widgets/header/header.tsx
  frontend/src/widgets/header/ui/nav-toolbar.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
Labels: Review effort [1-5]: 3
