Repository itsproutorgua/olx-killer-monorepo, pull requests merged in 2024-12, with the labels that each got.

#34 fixed sort values and logic
  frontend/src/entities/product/api/product.api.ts
  frontend/src/features/sort-button/model/consts.ts
  frontend/src/features/sort-button/model/index.ts
  frontend/src/features/sort-button/model/sort.types.ts
  frontend/src/features/sort-button/model/types.ts
  frontend/src/features/sort-button/ui/sort-button.tsx
  frontend/src/pages/catalog/catalog-page.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/constants/app.const.ts
  frontend/src/shared/library/types/index.ts
  frontend/src/shared/library/utils/generate-crumbs.ts
  frontend/src/widgets/best-deals/best-deals.tsx
  frontend/src/widgets/new-products/new-products.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/src/widgets/scrollable-product-list/scrollable-product-list.tsx
Labels: Review effort [1-5]: 2

#35 Update consts.ts
  frontend/src/features/sort-button/model/consts.ts
Labels: Review effort [1-5]: 1

#36 Favorites/functionality
  frontend/src/entities/favorite/api/favorite.api.ts
  frontend/src/entities/favorite/library/hooks/use-favorites.tsx
  frontend/src/entities/favorite/model/favorite.types.ts
  frontend/src/entities/product/model/product.types.ts
  frontend/src/entities/user/library/hooks/use-id-token.tsx
  frontend/src/features/add-to-favorite/ui/add-to-favorite.tsx
  frontend/src/shared/constants/query-keys.const.ts
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/favorite-button/favorite-button.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/product-card/ui/product-card.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
Labels: Review effort [1-5]: 4

#38 Page param removed from category api
  frontend/src/entities/category/api/category.api.ts
  frontend/src/entities/category/library/hooks/use-categories.tsx
  frontend/src/widgets/aside-nav/aside-nav.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
Labels: Review effort [1-5]: 2

#39 styles fixes
  frontend/src/features/add-to-favorite/ui/add-to-favorite.tsx
  frontend/src/features/top-bar/top-bar.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/widgets/favorite-button/favorite-button.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
Labels: Review effort [1-5]: 2

#40 Login refresh bug fixed, styles improved
  frontend/src/app/main.tsx
  frontend/src/app/providers/providers.tsx
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/product/write-seller/write-seller.tsx
  frontend/src/shared/assets/baner.svg
  frontend/src/shared/assets/images/banner/baner.png
  frontend/src/shared/assets/index.ts
  frontend/src/shared/ui/breadcrumbs.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/login-card/login-card.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/promo/promo.tsx
Labels: Review effort [1-5]: 3

#41 styles changes on product page
  frontend/src/features/top-bar/top-bar.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/product-details/product-details.tsx
  frontend/src/widgets/product-details/ui/contact-seller-card.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/product-details/ui/product-seller.tsx
Labels: Review effort [1-5]: 4

#43 add some suggestion
  frontend/src/entities/filter/library/hooks/use-filters-from-params.tsx
  frontend/src/features/filters-bar/ui/form/price-form.tsx
  frontend/src/widgets/page-toolbar/ui/filter-tags.tsx
  frontend/src/widgets/product-grid/ui/product-grid.tsx
Labels: Review effort [1-5]: 3

#44 removed backend-registration-api and bugs/styles fixes
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/product/library/hooks/use-product.tsx
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/product/write-seller/write-seller.tsx
  frontend/src/shared/ui/loaders/popular-categories.loader.tsx
  frontend/src/shared/ui/skeletons/popular-category-skeleton.tsx
  frontend/src/widgets/hero/mock/hero.mock.ts
  frontend/src/widgets/hero/ui/hero-slider.tsx
  frontend/src/widgets/product-details/ui/contact-seller-card.tsx
Labels: Review effort [1-5]: 4

#45 basic layout for account pages added
  frontend/src/app/main.tsx
  frontend/src/app/routes/private-routes.tsx
  frontend/src/app/routes/routes.tsx
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/add-to-favorite/ui/add-to-favorite.tsx
  frontend/src/pages/chat/chat-page.tsx
  frontend/src/pages/favorites/favorites-page.tsx
  frontend/src/pages/layouts/account-layout.tsx
  frontend/src/pages/layouts/index.ts
  frontend/src/pages/listings/listings-page.tsx
  frontend/src/pages/settings/settings-page.tsx
  frontend/src/shared/assets/images/account/inbox-empty.png
  frontend/src/shared/assets/index.ts
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/account-sidebar.const.ts
  frontend/src/shared/constants/page.const.ts
  frontend/src/shared/ui/icons/arrow-left-red.tsx
  frontend/src/shared/ui/icons/danger-icon.tsx
  frontend/src/shared/ui/icons/favorites-icon.tsx
  frontend/src/shared/ui/icons/messages-icon.tsx
  frontend/src/shared/ui/icons/pen-icon-rounded.tsx
  frontend/src/shared/ui/icons/profile-icon.tsx
  frontend/src/shared/ui/icons/settings-icon.tsx
  frontend/src/widgets/account/account-sidebar/account-sidebar.tsx
  frontend/src/widgets/account/empty-inbox/empty-inbox.tsx
  frontend/src/widgets/favorite-button/favorite-button.tsx
  frontend/src/widgets/product-slider/product-slider.tsx
  frontend/tailwind.config.ts
Labels: Review effort [1-5]: 4

#46 listings page created and styles fixed
  frontend/src/app/routes/private-routes.tsx
  frontend/src/entities/product/model/product.types.ts
  frontend/src/entities/user/api/user-listings.api.ts
  frontend/src/entities/user/library/hooks/use-listings.tsx
  frontend/src/entities/user/model/types.ts
  frontend/src/pages/listings/listings-page.tsx
  frontend/src/pages/product/product-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/listings-tabs.const.ts
  frontend/src/shared/constants/page.const.ts
  frontend/src/shared/constants/query-keys.const.ts
  frontend/src/shared/ui/icons/chat-icon.tsx
  frontend/src/shared/ui/icons/delete-small.tsx
  frontend/src/shared/ui/icons/edit-small.tsx
  frontend/src/shared/ui/icons/x-circle-small.tsx
  frontend/src/widgets/footer/footer.tsx
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
  frontend/src/widgets/product-card/ui/horizontal-product-card.tsx
  frontend/src/widgets/product-card/ui/product-card.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
  frontend/src/widgets/product-details/ui/product-location.tsx
  frontend/src/widgets/product-details/ui/product-seller.tsx
  frontend/src/widgets/promo/promo.tsx
Labels: Review effort [1-5]: 4

#47 chat page markup
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/chat/assets/msg-img.jpg
  frontend/src/features/chat/assets/photo.jpg
  frontend/src/features/chat/index.ts
  frontend/src/features/chat/library/index.ts
  frontend/src/features/chat/model/chat.data.ts
  frontend/src/features/chat/model/index.ts
  frontend/src/features/chat/model/message.data.ts
  frontend/src/features/chat/model/msg.data.ts
  frontend/src/features/chat/ui/chat-list.tsx
  frontend/src/features/chat/ui/chat-search.tsx
  frontend/src/features/chat/ui/chat-wrapper.tsx
  frontend/src/features/chat/ui/index.ts
  frontend/src/features/chat/ui/message-form.tsx
  frontend/src/features/chat/ui/message-header.tsx
  frontend/src/features/chat/ui/message-list.tsx
  frontend/src/features/chat/ui/scroll-to-button.tsx
  frontend/src/pages/chat/chat-page.tsx
  frontend/src/pages/layouts/account-layout.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/ui/icons/arrow-down-small.tsx
  frontend/src/shared/ui/icons/attach.tsx
  frontend/src/shared/ui/icons/checked-double.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/phone.tsx
  frontend/src/shared/ui/icons/send.tsx
  frontend/src/shared/ui/shadcn-ui/avatar.tsx
  frontend/src/shared/ui/shadcn-ui/input.tsx
  frontend/src/shared/ui/shadcn-ui/scroll-area.tsx
  frontend/src/shared/ui/shadcn-ui/textarea.tsx
  frontend/tailwind.config.ts
Labels: Review effort [1-5]: 4

#48 Empty listings page now correctly shows according to api, and bugfixes
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/announcement/add-announcement/add-announcement.tsx
  frontend/src/features/announcement/ui/add-listing-button.tsx
  frontend/src/pages/layouts/account-layout.tsx
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/widgets/account/account-sidebar/account-sidebar.tsx
  frontend/src/widgets/account/empty-inbox/empty-inbox.tsx
  frontend/src/widgets/hero/ui/hero-slider.tsx
Labels: Review effort [1-5]: 3

#49 Bug card #88/account/icons, README.md updated
  README.md
  frontend/README.md
  frontend/src/shared/constants/account-sidebar.const.ts
  frontend/src/shared/ui/icons/favorites-icon-outline.tsx
  frontend/src/shared/ui/icons/messages-icon-outline.tsx
  frontend/src/shared/ui/icons/pen-icon-rounded-outline.tsx
  frontend/src/shared/ui/icons/profile-icon-outline.tsx
  frontend/src/shared/ui/icons/settings-icon-outline.tsx
  frontend/src/widgets/account/account-sidebar/account-sidebar.tsx
Labels: Review effort [1-5]: 4
