Repository itsproutorgua/olx-killer-monorepo, pull requests merged in 2025-02, with the labels that each got.

#63 Add listing form created according to design, validation implemented.
  frontend/package-lock.json
  frontend/src/app/styles/index.css
  frontend/src/features/account/listings/index.ts
  frontend/src/features/account/listings/library/form-schema.tsx
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/features/account/listings/ui/dnd-grid.tsx
  frontend/src/features/account/listings/ui/dnd-sortable-item.tsx
  frontend/src/shared/config/i18next/translations/partials/errors.trans.ts
  frontend/src/shared/config/i18next/translations/partials/listing-form.trans.ts
  frontend/src/shared/ui/icons/video-upload-icon.tsx
  frontend/src/shared/ui/shadcn-ui/form.tsx
  frontend/src/shared/ui/shadcn-ui/input.tsx
Labels: Review effort [1-5]: 4

#64 Profile page with edit form for mobile and desktop added
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/features/account/listings/ui/dnd-grid.tsx
  frontend/src/features/account/profile/index.ts
  frontend/src/features/account/profile/library/profile-form-schema.tsx
  frontend/src/features/account/profile/ui/profile-data.tsx
  frontend/src/features/account/profile/ui/profile-edit-form.tsx
  frontend/src/pages/account/account-page-mobile.tsx
  frontend/src/pages/account/profile/profile-page.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/partials/crumb.trans.ts
  frontend/src/shared/config/i18next/translations/partials/profile-form.trans.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/ui/icons/edit-avatar-icon.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/page-wrapper.tsx
Labels: Review effort [1-5]: 4

#65 Some titles translations fixed, other minor styles fixes
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/widgets/category-popular/category-popular.tsx
  frontend/src/widgets/new-products/ui/new-products-slider.tsx
  frontend/src/widgets/other-products-by-seller/ui/products-by-seller-slider.tsx
  frontend/src/widgets/similar-products/ui/similar-products-slider.tsx
Labels: Review effort [1-5]: 2

#66 Create listing and profile edit forms modified, bugfixes
  frontend/src/app/main.tsx
  frontend/src/features/account/listings/library/form-schema.tsx
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/features/account/profile/library/profile-form-schema.tsx
  frontend/src/features/account/profile/ui/profile-edit-form.tsx
  frontend/src/pages/account/account-page-mobile.tsx
  frontend/src/pages/account/favorites/favorites-page.tsx
  frontend/src/pages/layouts/account-layout.tsx
  frontend/src/pages/layouts/account-root-layout.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/partials/listing-form.trans.ts
  frontend/src/shared/config/i18next/translations/partials/profile-form.trans.ts
  frontend/src/widgets/mobile-bottom-bar/bottom-bar.tsx
Labels: Review effort [1-5]: 4

#67 Create product
  backend/apps/common/errors.py
  backend/apps/favorites/migrations/0001_initial.py
  backend/apps/favorites/migrations/0002_initial.py
  backend/apps/favorites/migrations/0003_initial.py
  backend/apps/locations/migrations/0001_initial.py
  backend/apps/locations/migrations/0002_initial.py
  backend/apps/locations/views/location.py
  backend/apps/products/admin/product.py
  backend/apps/products/migrations/0001_initial.py
  backend/apps/products/migrations/0002_initial.py
  backend/apps/products/models/__init__.py
  backend/apps/products/models/price/price.py
  backend/apps/products/models/product.py
  backend/apps/products/models/product_image.py
  backend/apps/products/serializers/category/category.py
  backend/apps/products/serializers/price/price.py
  backend/apps/products/serializers/product/product.py
  backend/apps/products/serializers/product/product_image.py
  backend/apps/products/serializers/product/product_video.py
  backend/apps/products/views/product.py
  backend/apps/users/migrations/0001_initial.py
  backend/apps/users/models/user.py
  backend/apps/users/serializers/profile.py
  backend/settings/base.py
  backend/settings/main.py
Labels: Review effort [1-5]: 5

#68 Listing form api integrated
  frontend/src/app/main.tsx
  frontend/src/entities/currency/api/currency.api.ts
  frontend/src/entities/currency/index.ts
  frontend/src/entities/currency/library/hooks/use-currencies.tsx
  frontend/src/entities/product/api/product.api.ts
  frontend/src/entities/product/library/hooks/use-create-product.tsx
  frontend/src/entities/product/model/product.types.ts
  frontend/src/features/account/listings/library/form-schema.tsx
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/features/account/listings/ui/currency-select.tsx
  frontend/src/features/account/listings/ui/dnd-grid.tsx
  frontend/src/features/product/login/login-button.tsx
  frontend/src/pages/account/listings/create/create-success.tsx
  frontend/src/pages/account/listings/create/index.ts
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/partials/listing-form.trans.ts
  frontend/src/shared/config/i18next/translations/partials/title.trans.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/page.const.ts
  frontend/src/shared/constants/query-keys.const.ts
  frontend/src/shared/ui/icons/facebook-solid-icon.tsx
  frontend/src/shared/ui/icons/index.ts
  frontend/src/shared/ui/icons/instagram-solid-icon.tsx
  frontend/src/shared/ui/icons/search-icon-listing-success.tsx
  frontend/src/shared/ui/icons/settings-listing-success-icon.tsx
  frontend/src/shared/ui/icons/success-icon.tsx
  frontend/src/shared/ui/icons/trend-arrow-icon.tsx
Labels: Review effort [1-5]: 4

#69 User update feature implemented
  frontend/src/entities/locations/api/location.api.ts
  frontend/src/entities/locations/index.ts
  frontend/src/entities/locations/library/hooks/use-locations.tsx
  frontend/src/entities/locations/model/types.ts
  frontend/src/entities/user/api/index.ts
  frontend/src/entities/user/api/user-profile.api.ts
  frontend/src/entities/user/hooks/use-update-profile.tsx
  frontend/src/entities/user/hooks/useUserProfile.tsx
  frontend/src/entities/user/index.ts
  frontend/src/entities/user/model/types.ts
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/account/listings/ui/category-select-dialog.tsx
  frontend/src/features/account/listings/ui/create-listing-form.tsx
  frontend/src/features/account/listings/ui/currency-select.tsx
  frontend/src/features/account/profile/library/profile-form-schema.tsx
  frontend/src/features/account/profile/ui/profile-data.tsx
  frontend/src/features/account/profile/ui/profile-edit-form.tsx
  frontend/src/features/filters-bar/mock/filters.mock.ts
  frontend/src/features/filters-bar/ui/form/condition-form.tsx
  frontend/src/shared/config/i18next/translations/en.ts
  frontend/src/shared/config/i18next/translations/partials/errors.trans.ts
  frontend/src/shared/config/i18next/translations/partials/listing-form.trans.ts
  frontend/src/shared/config/i18next/translations/partials/profile-form.trans.ts
  frontend/src/shared/config/i18next/translations/uk.ts
  frontend/src/shared/constants/query-keys.const.ts
  frontend/src/shared/library/hooks/index.ts
  frontend/src/shared/library/hooks/use-debounce.ts
  frontend/src/shared/ui/shadcn-ui/dialog.tsx
  frontend/tailwind.config.ts
Labels: Review effort [1-5]: 4

#70 default user picture added
  frontend/src/entities/user/user-menu.tsx
  frontend/src/features/account/profile/ui/profile-data.tsx
  frontend/src/features/account/profile/ui/profile-edit-form.tsx
  frontend/src/pages/account/account-page-mobile.tsx
  frontend/src/shared/assets/images/account/profileDefault.png
  frontend/src/shared/assets/index.ts
Labels: Review effort [1-5]: 3

#71 Profile form fixes, validation and DnD fixes
  frontend/src/features/account/listings/library/form-schema.tsx
  frontend/src/features/account/listings/ui/dnd-grid.tsx
  frontend/src/features/account/profile/ui/profile-edit-form.tsx
  frontend/src/shared/config/i18next/translations/partials/errors.trans.ts
Labels: Review effort [1-5]: 4

#80 React player for video added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/widgets/product-details/ui/product-carousel.tsx
Labels: Review effort 4/5

#92 Profile name validation issues fixed
  frontend/src/features/account/profile/library/profile-form-schema.tsx
Labels: Review effort 2/5
