Repository itsproutorgua/olx-killer-monorepo, pull requests merged in 2025-04, with the labels that each got.

#111 Chat integration
  frontend/src/features/chat/chat-context/chat-context.tsx
  frontend/src/features/chat/library/hooks/use-chat.tsx
  frontend/src/features/chat/library/utils/fetchUserId.ts
  frontend/src/features/chat/model/chat-types.ts
  frontend/src/features/chat/model/index.ts
  frontend/src/features/chat/ui/chat-list.tsx
  frontend/src/features/chat/ui/chat-wrapper.tsx
  frontend/src/features/chat/ui/message-form.tsx
  frontend/src/features/chat/ui/message-list.tsx
  frontend/src/features/product/write-seller/write-seller.tsx
  frontend/src/widgets/product-details/ui/contact-seller-card.tsx
  frontend/src/widgets/product-details/ui/product-info.tsx
Labels: Review effort 4/5

#120 fixed chatlist returning
  backend/apps/chat/serializers/chat.py
Labels: Review effort 2/5

#121 added username field
  backend/apps/chat/serializers/chat.py
Labels: Review effort 2/5

#122 fixed
  backend/apps/chat/serializers/chat.py
Labels: Review effort 1/5

#124 Fixed message status, fixed chat list returning, renamed field 'username'
  backend/apps/chat/consumers/consumers.py
  backend/apps/chat/serializers/chat.py
  backend/apps/chat/utils/messages.py
Labels: Review effort 3/5
